line-length = 100
indent-width = 4
target-version = "py311"

[lint]
select = ["ALL"]
ignore = [
  "BLE001",
  "DTZ002",
  "DTZ005",
  "DTZ007",
  "T201",
  "TRY300",
]
fixable = ["ALL"]
unfixable = []
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "lf"